version: "3"

services:
  go-discord-bot:
    image: mgerb/go-discord-bot:latest
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - ./:/bot
      - /usr/local/bin/youtube-dl:/usr/bin/youtube-dl
